### ISSUE TITLE
ROS2 Support

### ISSUE THREAD

**Issue by mikeferguson** [mikeferguson/graceful_controller#10]
In progress, putting this here to track:

 * [x] Port controller to ROS2 (tested on UBR-1 with Humble)
 * [x] Get orientation tests working in ROS2
 * [x] Get graceful controller tests working in ROS2
 * [x] Merge into a "ros2" branch

**Comment by SteveMacenski** [comment]
I see you're doing some work on this -- my 2022 goals for Nav2 are surrounding navigation behaviors and controllers. Do you feel this work would enable a new niche or solve some existing problem with the controllers available or soon to be available in Nav2 (e.g. DWB, Reg. Pure Pursuit, and soon to be Model Predictive Path Integral Controller)? I'd love to hear your thoughts on this and if this would be something I should consider putting resources to porting in ROS 2 and having support for within Nav2

**Comment by mikeferguson** [comment]
First off - status in ROS2 - it works (at least on Foxy) - I haven't updated it since then. There are a number of enhancements since I did the port but those won't take too long to move over from ROS1 - I'm actually planning to do that later this month. The bigger effort might be migrating the tests - although I believe since I first ported this there has been a bunch of work on handling launch-based tests in ROS2.

Second - why does this exist? For differential drive robots, I find it to be more "predictable" than DWA. That said, if your robot is not circular in footprint, you absolutely need a planner that is kinematics aware (SBPL, or probably the new nav2_smac_lattice, which I've only briefly looked at).

**Comment by SteveMacenski** [comment]
This is doing direct path tracking comparable to a Pure Pursuit algorithm - quickly glancing over it I see strong similarities between it and RPP we added in the last ~18 months to Nav2 (https://github.com/ros-planning/navigation2/tree/main/nav2_regulated_pure_pursuit_controller). RPP is essentially just Pure Pursuit with heuristics applied for (1) reducing speed in high curvature turns and (2) reducing speed in close proximity to obstacles. 

Did you compare this with a PP algorithm and preferred the behavior of this instead? I have little beef potentially moving to another solution if its preferable, RPP has turned a little Frankenstein over time and I am drawn the simplicity of this work. 

Porting status isn't too important to me, it doesn't take much time to move things over.  

PS the [smac planner](https://github.com/ros-planning/navigation2/tree/main/nav2_smac_planner) has both a Hybrid-A* and State Lattice planner that are kinematically aware. Both are approximately run-time comparable to NavFn.

**Comment by mikeferguson** [comment]
Update: latest code is ported (and tested) on ROS2. There is one remaining test that is ported but not yet working (and so commented out) - due to an issue I've posted here: https://answers.ros.org/question/402229/problem-reserving-cachechange-in-reader/

**Comment by mikeferguson** [comment]
Last test is now working - https://github.com/mikeferguson/graceful_controller/pull/48

There are a few new features getting added to the ROS1 branch that are in process of being ported, but plan to have a ROS2 Debian release next week
