### ISSUE TITLE
Controller for docking

### ISSUE THREAD

**Issue by jcarlosgm30** [mikeferguson/graceful_controller#72]
Hello @mikeferguson ,

What do you think about using this controller for docking? It has features that make it interesting for it. I don't know if it makes sense to add certain parameters to help docking, such as removing it from rotating when it reaches the target pose or disabling the collision checker.

BR,
JC

**Comment by mikeferguson** [comment]
The control law (in the LGPL licensed package graceful_controller) actually came from https://github.com/ZebraDevs/fetch_open_auto_dock, the graceful_controller_ros just wraps the underlying control law and makes it do all the added things required for local control with the navigation stack.

**Comment by jcarlosgm30** [comment]
So, then if we wanted to use it for docking, we would have to make a different "wrapper" to graceful_controller_ros, since modifying the current one to make it work in both cases would be unfeasible, right?

**Comment by mikeferguson** [comment]
If you haven't seen it already, you should check out the new docking server in nav2 - it uses the same control law.
